Repository fresh2you/fresh2you-frontend, pull requests merged in 2024-10, with the labels that each got.

#38 Design: 상품 상세 페이지 스타일링 변경
  src/pages/product/ProductDetailPage.jsx
  src/pages/product/components/details/ProductInfo.jsx
  src/pages/product/components/skeletons/ProductDetailSkeleton.jsx
Labels: Design

#39 Refactor/UI/chatting
  src/assets/icons/arrow-down.svg
  src/assets/icons/arrow-left-sm.svg
  src/assets/icons/arrow-right-sm.svg
  src/assets/img/iconoir--profile-circle.svg
  src/components/pageLayout/PageLayout.tsx
  src/mockdata/db.json
  src/pages/chat/ChatListPage.jsx
  src/pages/chat/ChatPage.jsx
  src/pages/chat/api/api.jsx
  src/pages/chat/api/chatApis.jsx
  src/pages/chat/components/ChatFooter.jsx
  src/pages/chat/components/ChatHeader.jsx
  src/pages/chat/components/ChatItem.jsx
  src/pages/chat/components/DropDownMenu.jsx
  src/pages/chat/components/MessageItem.jsx
  src/pages/chat/components/MessageList.jsx
  src/pages/chat/hooks/useChatMessages.js
  src/pages/chat/hooks/useMaxLenByScreenRation.js
  src/pages/chat/hooks/useScrollToBottom.js
  src/pages/product/api/productApis.js
  src/pages/product/components/ProductCard.jsx
  src/pages/product/components/buttons/ProductActionButtons.jsx
  src/pages/product/components/details/ProductInfo.jsx
  src/pages/product/hooks/useInitialRender.js
  src/stores/product.js
  src/utils/commonUtils.jsx
  yarn.lock
Labels: refactor

#40 Fix & Refactor: 타입 수정 & authAPI 수정 & 로그인/소셜 회원가입 로직 수정
  src/components/layout/components/MenuDropDown.tsx
  src/pages/redirection/RedirectionPage.jsx
  src/pages/signIn/SignInPage.jsx
  src/pages/signIn/api/kakaoLogin.js
  src/pages/signIn/api/kakaoLogin.jsx
  src/pages/signIn/api/signIn.js
  src/pages/signIn/handler/handleSubmit.js
  src/pages/signIn/hooks/useKakaoLogin.jsx
  src/pages/signIn/hooks/useLogin.js
  src/pages/signIn/utils/authUtils.jsx
  src/pages/signUp/api/signUpUser.js
  src/pages/terms/TermsAgreementPage.jsx
  src/pages/terms/handler/handleSubmit.js
  src/services/api/authAPI.ts
  src/types/request/authRequest.d.ts
  src/types/response/memberResponse.d.ts
Labels: refactor, fix

#42 상품 페이지 최종 점검 및 개선 (상품 수정 제외)
  package.json
  src/assets/icons/plus.svg
  src/pages/product/PaymentCompletePage.jsx
  src/pages/product/ProductPurchasePage.jsx
  src/pages/product/ProductRegistrationPage.jsx
  src/pages/product/ProductsPage.jsx
  src/pages/product/api/productApis.js
  src/pages/product/components/ProductCard.jsx
  src/pages/product/components/ProductList.jsx
  src/pages/product/components/SubCategoryItems.jsx
  src/pages/product/components/buttons/CategoryButtons.jsx
  src/pages/product/components/purchase/PurchaseForm.jsx
  src/pages/product/components/registration/ProductForm.jsx
  src/pages/product/hooks/useDefaultAddress.js
  src/pages/product/utils/productUtils.js
Labels: fix

#43 유저 정보 관련 로직과 UI 수정 & 추천 상품 가져오는 로직 수정
  src/components/layout/components/HeaderRight.tsx
  src/components/layout/components/HeaderUserInfo.tsx
  src/mockdata/MockData.ts
  src/mockdata/homeMockData.ts
  src/mockdata/searchMockData.ts
  src/pages/home/HomePage.tsx
  src/pages/home/component/Banner.tsx
  src/pages/home/component/ProductCard.tsx
  src/pages/home/hooks/useHomePageLogics.tsx
  src/pages/mypage/mypage/MyPage.tsx
  src/pages/mypage/mypage/components/MenuButton.tsx
  src/pages/mypage/mypage/components/MyPageHeader.tsx
  src/pages/mypage/mypage/components/MyPageUserInfo.tsx
  src/pages/mypage/mypage/components/MyPageUserMenu.tsx
  src/pages/mypage/mypage/hooks/useMyPageLogics.tsx
  src/services/api/userAPI.ts
Labels: refactor, fix, Design

#48 배포 환경에서도 소셜로그인 시 localhost로 redirect되는 이슈 해결
  src/pages/signIn/hooks/useKakaoLogin.jsx
  src/pages/signIn/utils/authUtils.jsx
  src/styles/GlobalStyles.tsx
Labels: hotfix

#45 auth 관련 페이지 최종 점검 및 개선
  src/pages/signIn/SignInPage.jsx
  src/pages/signIn/components/InputField.jsx
  src/pages/signIn/components/SignInForm.jsx
  src/pages/signUp/SignUpComplete.jsx
  src/pages/signUp/SignUpPage.jsx
  src/pages/signUp/api/verifications.js
  src/pages/signUp/component/InputField.jsx
  src/pages/signUp/component/StepFields.jsx
  src/pages/signUp/component/buttons/NextBtn.jsx
  src/pages/signUp/utils/handlers/handleEmailCheck.jsx
  src/pages/terms/handler/handleSubmit.js
  src/styles/styles.css
Labels: fix, Design

#46 FIX: 판매자 여부 판별하기 위해 사용자 정보 fetch
  src/pages/product/ProductsPage.jsx
Labels: fix

#49 채팅 UI 개선, 웹소켓 연결
  index.html
  src/assets/img/fallback.png
  src/assets/img/favicon.ico
  src/assets/img/favicon.png
  src/pages/chat/ChatListPage.jsx
  src/pages/chat/ChatPage.jsx
  src/pages/chat/api/chatApis.jsx
  src/pages/chat/api/stomp.js
  src/pages/chat/components/ChatFooter.jsx
  src/pages/chat/components/ChatItem.jsx
  src/pages/chat/components/MessageItem.jsx
  src/pages/chat/hooks/useChatMessages.js
  src/pages/chat/hooks/useChatRooms.js
  src/pages/chat/hooks/useScrollToBottom.js
  src/pages/product/ProductDetailPage.jsx
  src/pages/product/components/buttons/ProductActionButtons.jsx
  src/pages/product/components/details/ProductInfo.jsx
Labels: fix, Design

#50 HOTFIX: 약관동의 데이터 저장 방법 변경
  src/pages/signUp/SignUpPage.jsx
  src/pages/terms/handler/handleSubmit.js
Labels: hotfix

#51 포인트 충전 과 프로필 변경 수정
  src/pages/mypage/charge/PointPage.tsx
  src/pages/mypage/charge/hooks/usePointPagelogics.tsx
  src/pages/mypage/mypage/components/MyPageUserInfo.tsx
  src/pages/mypage/profile/ChangeProfilePage.tsx
  src/pages/mypage/profile/hooks/useChangeProfilePageLogics.ts
  src/services/api/userAPI.ts
Labels: fix

#52 프로필 변경과 배송지 관련 API 수정 작업
  src/pages/mypage/deliveries/DeliveriesPage.tsx
  src/pages/mypage/deliveries/components/AddDeliveryModal.tsx
  src/pages/mypage/deliveries/components/DaumAddressModal.tsx
  src/pages/mypage/deliveries/components/DeliveryBox.tsx
  src/pages/mypage/deliveries/hooks/useAddDeliveryModalLogics.tsx
  src/pages/mypage/deliveries/hooks/useDeliveriesPageLogics.tsx
  src/pages/mypage/profile/hooks/useChangeProfilePageLogics.ts
  src/services/api/userAPI.ts
Labels: fix

#53 판매자 인증 관련 UI & 로직 수정
  src/pages/mypage/mypage/components/MyPageUserInfo.tsx
  src/pages/mypage/verifySeller/VerifySellerPage.tsx
  src/pages/mypage/verifySeller/hooks/useVerifySellerPageLogics.tsx
  src/services/api/userAPI.ts
Labels: fix

#54 fix: 검색 기능 API 배포 연결
  src/components/ProductBox.tsx
  src/pages/search/SearchPage.tsx
  src/pages/search/hooks/useSearchPageLogics.tsx
Labels: fix

#59 fix: 상품페이지와 채팅페이지에서 사용자정보가 페칭되기 전에 데이터의 속성값에 바로 접근하는 코드 수정
  src/pages/chat/ChatListPage.jsx
  src/pages/chat/ChatPage.jsx
  src/pages/product/ProductsPage.jsx
Labels: fix

#60 Refactor: 상품 페이지 리팩토링
  src/global.d.ts
  src/pages/product/ProductDetailPage.tsx
  src/pages/product/ProductPurchasePage.tsx
  src/pages/product/ProductsPage.tsx
  src/pages/product/components/ProductCard.tsx
  src/pages/product/components/ProductList.tsx
  src/pages/product/components/details/ProductDescription.jsx
  src/pages/product/components/details/ProductDescription.tsx
  src/pages/product/components/details/ProductDetailSection.tsx
  src/pages/product/components/details/ProductImageSlider.tsx
  src/pages/product/components/details/ProductInfo.tsx
  src/pages/product/components/skeletons/ProductDetailSkeleton.tsx
  src/pages/product/hooks/useFetchProductById.js
  src/pages/product/hooks/useFetchProductById.ts
  src/services/api/productAPI.ts
  src/types/response/productsResponse.d.ts
Labels: refactor

#61 채팅방 리스트 페이지 tsx로 변환, UI 수정
  src/assets/img/fallback.png
  src/assets/img/fallback.svg
  src/mockdata/chatListMockData.ts
  src/pages/chat/ChatListPage.jsx
  src/pages/chat/ChatListPage.tsx
  src/pages/chat/ChatPage.jsx
  src/pages/chat/ChatPage.tsx
  src/pages/chat/components/ChatItem.jsx
  src/pages/chat/components/ChatItem.tsx
  src/pages/chat/components/ParticipantImages.tsx
  src/pages/chat/hooks/useChatPage.ts
  src/pages/chat/hooks/useChatRoomName.ts
  src/pages/chat/hooks/useChatRooms.js
  src/pages/chat/hooks/useChatRooms.ts
  src/pages/chat/hooks/useMaxLenByScreenRation.ts
  src/pages/chat/utils/formatDate.ts
  src/pages/chat/utils/getTruncatedMessage.ts
  src/pages/product/PaymentCompletePage.jsx
  src/pages/search/hooks/useSearchPageLogics.tsx
  src/types/chat/chatTypes.d.ts
Labels: feat, fix, Design

#62 제품 페이지 비지니스 로직과 UI 로직 분리및 리팩토링
  src/hooks/useHeaderProps.ts
  src/pages/product/ProductDetailPage.tsx
  src/pages/product/ProductPurchasePage.tsx
  src/pages/product/ProductRegistrationPage.jsx
  src/pages/product/ProductsPage.tsx
  src/pages/product/api/productApis.js
  src/pages/product/atom/atom.ts
  src/pages/product/components/ProductCard.tsx
  src/pages/product/components/SubCategoryItems.tsx
  src/pages/product/components/buttons/CategoryButtons.jsx
  src/pages/product/components/buttons/CategoryButtons.tsx
  src/pages/product/components/details/ItemNotFound.tsx
  src/pages/product/components/skeletons/ProductCardSkeleton.tsx
  src/pages/product/hooks/useCategoryLogic.ts
  src/pages/product/hooks/useDefaultAddress.ts
  src/pages/product/hooks/useFetchCategories.js
  src/pages/product/hooks/useFetchCategories.ts
  src/pages/product/hooks/useFetchProductById.ts
  src/pages/product/hooks/useInfiniteScroll.ts
  src/pages/product/hooks/useInitialRender.js
  src/pages/product/hooks/useProductPageLogic.ts
  src/pages/product/utils/categoryHandlers.ts
  src/pages/product/utils/loadProducts.ts
  src/pages/product/utils/productUtils.js
  src/pages/product/utils/renderComponent.tsx
  src/services/api/productAPI.ts
  src/types/product/productProps.ts
  src/types/product/productTypes.d.ts
Labels: refactor, fix
