Repository fresh2you/fresh2you-frontend, pull requests merged in 2024-09, with the labels that each got.

#6 Feat/#3 home
  package.json
  src/assets/icons/icon-account.svg
  src/assets/icons/icon-chat.svg
  src/assets/icons/icon-community.svg
  src/assets/icons/icon-home.svg
  src/assets/icons/icon-product.svg
  src/assets/icons/icon-search.svg
  src/assets/logo.png
  src/components/layout/FooterNavBar.tsx
  src/components/layout/Header.tsx
  src/components/layout/RootLayout.tsx
  src/components/layout/components/Menu.tsx
  src/index.css
  src/mockdata/homeMockData.ts
  src/pages/home/HomePage.tsx
  src/pages/home/component/Banner.tsx
  src/pages/home/component/ProductCard.tsx
  src/routes/Router.tsx
  vite.config.ts
  yarn.lock
Labels: feat

#8 Origin/feat/#5 auth
  package.json
  src/assets/icons/block.svg
  src/assets/img/kakaotalk.png
  src/assets/img/logo.png
  src/pages/signIn/SignInPage.jsx
  src/pages/signIn/components/InputField.jsx
  src/pages/signIn/components/Redirection.jsx
  src/pages/signIn/components/SignInForm.jsx
  src/pages/signIn/utils/authUtils.jsx
  src/pages/signUp/SignUpPage.jsx
  src/pages/signUp/component/ErrorMessage.jsx
  src/pages/signUp/component/InputField.jsx
  src/pages/signUp/component/NextButton.jsx
  src/pages/signUp/component/PasswordFeedback.jsx
  src/pages/signUp/component/StepFields.jsx
  src/pages/signUp/stepsConfig.jsx
  src/pages/signUp/utils/handleSubmit.jsx
  src/pages/signUp/utils/validationUtils.jsx
  src/routes/Router.tsx
  src/services/api2.jsx
  src/styles/styles.css
  tailwind.config.js
  yarn.lock
Labels: feat

#9 Feat: 검색페이지 UI & 기능 구현
  src/components/DropDown.tsx
  src/components/DropDownOption.tsx
  src/components/layout/Header.tsx
  src/components/layout/components/HeaderInput.tsx
  src/mockdata/searchMockData.ts
  src/pages/search/SearchPage.tsx
  src/pages/search/components/SearchedItemBox.tsx
  src/pages/search/hooks/useSearchPageLogics.tsx
  src/routes/Router.tsx
Labels: feat

#15 chore: 프로젝트 세팅 완료
  .gitignore
  .prettierrc
  .vscode/settings.json
  README.md
  package.json
  src/components/layout/components/HeaderInput.tsx
  src/instance.ts
  src/mockdata/db.json
  src/pages/home/HomePage.tsx
  src/pages/home/component/ProductCard.tsx
  src/pages/home/hooks/useHomePageLogics.tsx
  src/pages/search/hooks/useSearchPageLogics.tsx
  src/services/api.ts
  src/services/api/userAPI.ts
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: chore

#19 Feat: 마이페이지 UI & 기능 일부 구현
  src/App.css
  src/assets/icons/arrow-left.svg
  src/assets/icons/carbonBox.svg
  src/assets/icons/change.svg
  src/assets/icons/delivery.svg
  src/assets/icons/eye.svg
  src/assets/icons/heart.svg
  src/assets/icons/list.svg
  src/assets/icons/logout.svg
  src/components/CommonHeader.tsx
  src/components/InputWithLabel.tsx
  src/components/ProductBox.tsx
  src/components/layout/Header.tsx
  src/components/layout/components/Menu.tsx
  src/global.d.ts
  src/index.css
  src/main.tsx
  src/mockdata/db.json
  src/pages/home/HomePage.tsx
  src/pages/home/component/Banner.tsx
  src/pages/mypage/charge/PointPage.tsx
  src/pages/mypage/charge/hooks/usePointPagelogics.tsx
  src/pages/mypage/components/MyPageLayout.tsx
  src/pages/mypage/likes/LikeListpage.tsx
  src/pages/mypage/likes/hooks/useLikeListPageLogics.tsx
  src/pages/mypage/mypage/MyPage.tsx
  src/pages/mypage/mypage/components/MenuButton.tsx
  src/pages/mypage/mypage/components/MyPageHeader.tsx
  src/pages/mypage/mypage/components/MyPageUserInfo.tsx
  src/pages/mypage/mypage/components/MyPageUserMenu.tsx
  src/pages/mypage/mypage/hooks/useMyPageLogics.tsx
  src/pages/mypage/password/ChangePasswordPage.tsx
  src/pages/mypage/verifySeller/VerifySellerPage.tsx
  src/pages/mypage/verifySeller/hooks/useVerifySellerPageLogics.tsx
  src/pages/search/SearchPage.tsx
  src/routes/Router.tsx
  src/stores/mypage.ts
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: feat

#22 Feat: 마이페이지 UI & 기능 일부 구현
  src/assets/icons/camera.svg
  src/components/BackButton.tsx
  src/components/CommonHeader.tsx
  src/hooks/useCommon.ts
  src/pages/mypage/likes/LikeListpage.tsx
  src/pages/mypage/mypage/hooks/useMyPageLogics.tsx
  src/pages/mypage/profile/ChangeProfilePage.tsx
  src/pages/mypage/profile/hooks/useChangeProfilePageLogics.ts
  src/pages/mypage/verifySeller/hooks/useVerifySellerPageLogics.tsx
  src/routes/Router.tsx
Labels: feat

#25 Feat: 마이페이지 - 배송지관리 페이지 구현
  package.json
  src/App.tsx
  src/components/InputWithLabel.tsx
  src/mockdata/db.json
  src/pages/mypage/deliveries/DeliveriesPage.tsx
  src/pages/mypage/deliveries/components/AddDeliveryModal.tsx
  src/pages/mypage/deliveries/components/DaumAddressModal.tsx
  src/pages/mypage/deliveries/components/DeliveryBox.tsx
  src/pages/mypage/deliveries/hooks/useAddDeliveryModalLogics.tsx
  src/pages/mypage/deliveries/hooks/useDeliveriesPageLogics.tsx
  src/pages/mypage/likes/LikeListPage.tsx
  src/routes/Router.tsx
  yarn.lock
Labels: feat

#26 Refactor: 전역 레이아웃에 반응형 적용
  src/assets/icons/chevron-right.svg
  src/assets/icons/icon-chat.svg
  src/assets/icons/icon-home.svg
  src/assets/icons/icon-product.svg
  src/assets/icons/icon-search.svg
  src/assets/icons/menu.svg
  src/assets/icons/x-close.svg
  src/assets/img/logo-text.svg
  src/components/layout/FooterNavBar.tsx
  src/components/layout/Header.tsx
  src/components/layout/RootLayout.tsx
  src/components/layout/components/FooterMenu.tsx
  src/components/layout/components/HeaderCenterMenus.tsx
  src/components/layout/components/HeaderInput.tsx
  src/components/layout/components/HeaderRight.tsx
  src/components/layout/components/HeaderUserInfo.tsx
  src/components/layout/components/MenuDropDown.tsx
  src/components/layout/components/MenuDropDownOption.tsx
  src/components/layout/constants/menus.tsx
  src/index.css
  tailwind.config.js
Labels: refactor

#28 Fix: 반응형 루트 레이아웃과 페이지 레이아웃 적용
  package.json
  src/components/CommonHeader.tsx
  src/components/layout/FooterNavBar.tsx
  src/components/layout/components/HeaderRight.tsx
  src/components/layout/components/HeaderUserInfo.tsx
  src/components/layout/components/MenuDropDown.tsx
  src/components/layout/constants/menus.tsx
  src/components/pageLayout/PageLayout.tsx
  src/components/pageLayout/PageLayoutHeader.tsx
  src/hooks/useCommon.ts
  src/pages/NotfoundPage.jsx
  src/pages/mypage/components/MyPageLayout.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/Router.tsx
  src/stores/mypage.ts
  src/utils/storageUtils.ts
  yarn.lock
Labels: feat

#31 Hotfix: 약관 데이터 이스케이프 해제
  src/pages/terms/components/TermsAgreement.jsx
Labels: hotfix

#32 feat: API 응답 타입 정의 & 헤더에 토큰 보내는 분기 처리
  src/instance.ts
  src/types/response/backend.d.ts
  src/types/response/communityResponse.d.ts
  src/types/response/memberResponse.d.ts
  src/types/response/productsResponse.d.ts
  src/types/response/termsResponse.d.ts
  src/types/response/verifyResponse.d.ts
Labels: feat

#35 Design: 레이아웃 적용 여부에 따른 로딩 컴포넌트 스타일링 수정
  src/pages/product/ProductPurchasePage.jsx
  src/pages/redirection/RedirectionPage.jsx
  src/pages/redirection/component/Loading.jsx
  src/pages/signUp/SignUpComplete.jsx
  src/pages/signUp/SignUpPage.jsx
Labels: Design

#37 fix: 제품 구매 버그 수정 & 스타일 수정
  src/pages/product/ProductPurchasePage.jsx
  src/pages/product/api/productApis.js
  src/pages/product/components/purchase/AddressModal.jsx
  src/pages/product/components/purchase/InputField.jsx
  src/pages/product/components/purchase/PurchaseForm.jsx
  src/pages/product/components/purchase/TextInput.jsx
  src/pages/product/hooks/useDefaultAddress.js
Labels: fix
