Repository fresh2you/fresh2you-frontend, pull requests merged in 2024-11, with the labels that each got.

#67 제품 페이지에 좋아요 기능 구현
  src/assets/icons/filled-heart.svg
  src/assets/icons/heart.svg
  src/pages/product/components/ProductCard.tsx
  src/pages/product/components/ProductList.tsx
  src/pages/product/components/details/ProductInfo.tsx
  src/pages/product/hooks/useFetchLikedProducts.ts
  src/pages/product/hooks/useInitialRender.ts
  src/pages/product/hooks/useLikedStatus.ts
  src/pages/product/utils/productDataUtils.ts
Labels: feat

#68 마이페이지 관련 페이지들 작업
  package.json
  src/App.tsx
  src/assets/font/Pretendard-Black.woff2
  src/assets/font/Pretendard-Bold.woff2
  src/assets/font/Pretendard-ExtraBold.woff2
  src/assets/font/Pretendard-ExtraLight.woff2
  src/assets/font/Pretendard-Light.woff2
  src/assets/font/Pretendard-Medium.woff2
  src/assets/font/Pretendard-Regular.woff2
  src/assets/font/Pretendard-SemiBold.woff2
  src/assets/font/Pretendard-Thin.woff2
  src/assets/font/font.css
  src/assets/icons/change.svg
  src/assets/icons/delivery.svg
  src/assets/icons/edit.svg
  src/assets/icons/logout.svg
  src/assets/icons/menu-changePW.svg
  src/assets/icons/menu-delivery.svg
  src/assets/icons/menu-heart.svg
  src/assets/icons/menu-logout.svg
  src/assets/icons/menu-product-list.svg
  src/assets/icons/menu-register.svg
  src/assets/icons/product-list.svg
  src/components/LoadingSpinner.tsx
  src/components/ProductBox.tsx
  src/components/WideProductBox.tsx
  src/components/layout/components/MenuDropDown.tsx
  src/components/pageLayout/PageLayout.tsx
  src/components/pageLayout/PageLayoutHeader.tsx
  src/components/types/type.WideProductBox.ts
  src/hooks/useIntersectionObserver.ts
  src/pages/mypage/charge/PointPage.tsx
  src/pages/mypage/charge/hooks/usePointPagelogics.tsx
  src/pages/mypage/deliveries/DeliveriesPage.tsx
  src/pages/mypage/deliveries/hooks/useAddDeliveryModalLogics.tsx
  src/pages/mypage/deliveries/hooks/useDeliveriesPageLogics.tsx
  src/pages/mypage/likes/LikeListPage.tsx
  src/pages/mypage/likes/hooks/useLikeListPageLogics.tsx
  src/pages/mypage/myProducts/MyProductsPage.tsx
  src/pages/mypage/myProducts/components/MyProductList.tsx
  src/pages/mypage/myProducts/hooks/useMyProductsPageLogics.ts
  src/pages/mypage/mypage/MyPage.tsx
  src/pages/mypage/mypage/components/MenuButton.tsx
  src/pages/mypage/mypage/components/MyPageHeader.tsx
  src/pages/mypage/mypage/components/MyPageUserInfo.tsx
  src/pages/mypage/mypage/hooks/useMyPageLogics.tsx
  src/pages/mypage/password/ChangePasswordPage.tsx
  src/pages/mypage/profile/ChangeProfilePage.tsx
  src/pages/mypage/profile/hooks/useChangeProfilePageLogics.ts
  src/pages/mypage/verifySeller/VerifySellerPage.tsx
  src/pages/mypage/verifySeller/hooks/useVerifySellerPageLogics.tsx
  src/pages/product/listing/hooks/useFetchLikedProducts.ts
  src/pages/search/SearchPage.tsx
  src/routes/Router.tsx
  src/services/api/productAPI.ts
  src/types/response/backend.d.ts
  src/types/response/productsResponse.d.ts
  src/utils/constants.ts
Labels: feat, refactor, fix

#73 [refactor] 마무리 작업
  src/components/InputWithLabel.tsx
  src/pages/product/common/components/LikeButton.tsx
  src/pages/product/detail/components/ProductInfo.tsx
  src/pages/product/listing/components/ProductCard.tsx
  src/pages/product/listing/hooks/useLikedStatus.ts
  src/pages/product/listing/utils/productDataUtils.ts
  src/pages/product/purchase/components/AddressList.tsx
  src/pages/signUp/SignUpPage.tsx
  src/pages/signUp/component/EmailVerificationModal.tsx
  src/pages/signUp/component/StepFields.tsx
  src/pages/signUp/component/buttons/NextBtn.tsx
  src/pages/signUp/component/fieldConfigs/createPasswordFieldConfig.tsx
  src/pages/signUp/component/fieldConfigs/useEmailFieldConfig.tsx
  src/pages/signUp/component/fieldConfigs/useNicknameFieldConfig.tsx
  src/pages/signUp/hooks/useAutoNext.ts
  src/pages/signUp/hooks/useEmailDupCheck.ts
  src/pages/signUp/hooks/useNicknameCheck.ts
  src/pages/signUp/hooks/usePasswordValidation.ts
  src/pages/signUp/hooks/useRequestVerificationCode.ts
  src/pages/signUp/hooks/useSignUpForm.ts
  src/pages/signUp/hooks/useSignup.ts
  src/pages/signUp/hooks/useVerifyEmailCode.ts
  src/pages/signUp/useStepsConfig.ts
  src/pages/signUp/utils/handlers/callbackHandlers.ts
  src/pages/signUp/utils/handlers/handleEmailCheck.ts
  src/pages/signUp/utils/handlers/handleNext.ts
  src/pages/signUp/utils/handlers/handleNicknameCheck.ts
  src/pages/signUp/utils/handlers/handleVerification.ts
  src/pages/signUp/utils/handlers/handleVerifyClick.ts
  src/pages/signUp/utils/passwordUtils.ts
  src/pages/signUpComplete/component/Slide.tsx
  src/pages/signUpComplete/component/SliderControls.tsx
  src/types/signUp/signUpTypes.d.ts
  src/utils/commonUtils.ts
Labels: refactor
